name: Test

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    strategy:
      fail-fast: false # Default value means that a failure in one OS cancels all 
      matrix:
        smalltalk: [ Pharo64-9.0, Pharo64-10 ]
        os: [ windows-latest ] # macos-latest, ubuntu-latest
        ston: [ .ci.ston ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load in new image and run SUnit tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.ston }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10
